# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x02\n\x10\x44oyenCandlestick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\'\n\x08\x65xchange\x18\x02 \x01(\x0e\x32\x15.common.DoyenExchange\x12\x0c\n\x04open\x18\n \x01(\x01\x12\x0c\n\x04high\x18\x0b \x01(\x01\x12\x0b\n\x03low\x18\x0c \x01(\x01\x12\r\n\x05\x63lose\x18\r \x01(\x01\x12\x12\n\nvolumeBase\x18\x14 \x01(\x01\x12\x13\n\x0bvolumeQuote\x18\x15 \x01(\x01\x12$\n\ttimeframe\x18\x32 \x01(\x0e\x32\x11.common.Timeframe\x12-\n\ttimestamp\x18< \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\ttimeStart\x18= \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07timeEnd\x18> \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nhistorical\x18\x64 \x01(\x08*\xfe\x02\n\rDoyenExchange\x12\x14\n\x10\x45XCHANGE_UNKNOWN\x10\x00\x12\x16\n\x12\x45XCHANGE_BINANCEUS\x10\x01\x12\x13\n\x0f\x45XCHANGE_KRAKEN\x10\x02\x12\x13\n\x0f\x45XCHANGE_GEMINI\x10\x03\x12\x15\n\x11\x45XCHANGE_COINBASE\x10\x04\x12\x16\n\x12\x45XCHANGE_CRYPTOCOM\x10\x05\x12\x13\n\x0f\x45XCHANGE_NONKYC\x10\x06\x12\x15\n\x11\x45XCHANGE_BITFLYER\x10\x07\x12\x11\n\rEXCHANGE_MEXC\x10\x08\x12\x14\n\x10\x45XCHANGE_APOLLOX\x10\t\x12\x10\n\x0c\x45XCHANGE_CEX\x10\n\x12\x15\n\x11\x45XCHANGE_BITSTAMP\x10\x0b\x12\x16\n\x12\x45XCHANGE_COINCHECK\x10\x0c\x12\x13\n\x0e\x45XCHANGE_CROSS\x10\xe4\x07\x12\x12\n\rEXCHANGE_IBKR\x10\xe5\x07\x12\x14\n\x0f\x45XCHANGE_SCHWAB\x10\xe6\x07\x12\x11\n\x0c\x45XCHANGE_ALL\x10\xe7\x07*\xbf\x01\n\tTimeframe\x12\x15\n\x11TIMEFRAME_UNKNOWN\x10\x00\x12\x18\n\x14TIMEFRAME_ONE_MINUTE\x10\x01\x12\x1a\n\x16TIMEFRAME_FIVE_MINUTES\x10\x02\x12\x1d\n\x19TIMEFRAME_FIFTEEN_MINUTES\x10\x05\x12\x16\n\x12TIMEFRAME_ONE_HOUR\x10\x14\x12\x17\n\x13TIMEFRAME_FOUR_HOUR\x10\x19\x12\x15\n\x11TIMEFRAME_ONE_DAY\x10\x32\x42\x14\xaa\x02\x11\x44oyen.gRPC.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021Doyen.gRPC.Common'
  _globals['_DOYENEXCHANGE']._serialized_start=430
  _globals['_DOYENEXCHANGE']._serialized_end=812
  _globals['_TIMEFRAME']._serialized_start=815
  _globals['_TIMEFRAME']._serialized_end=1006
  _globals['_DOYENCANDLESTICK']._serialized_start=58
  _globals['_DOYENCANDLESTICK']._serialized_end=427
# @@protoc_insertion_point(module_scope)
